'use client';

/**
 * DefinitionsSection — v0.4 §05 Australia Cold Chain Market Definitions
 *
 * @what  2-tab section (Key Market Definition · Fundamental Definitions) matching live
 *        kenresearch.com/australia-cold-chain-markets structure.
 *        Tab 1: 2 market-scope cards (Cold Chain Market · Cold Transport Market) ·
 *               quick-facts chips + prose + revenue streams bullets.
 *        Tab 2: 5 fundamental cards (Ambient · Frozen · Chiller · Captive · Non-Captive) ·
 *               temperature badge + range + def + in/out-of-scope tag.
 *
 * @why   Live page uses Radix Tabs · live-verified content (re-scraped 2026-05-21).
 *        Better than live by adding temperature visual + quick-facts chips + scope tag.
 *        Craft-pass applied · craft principle #1 hierarchy per section · #2 type rhythm
 *        tuned per content density. Drops generic AccordionListTemplate (wrong shape for
 *        mixed-length definition content).
 *
 * @when  v0.4 PDP body §05. Below Market Overview & Genesis.
 *
 * @how   DS atoms: SectionLabel (eyebrow accent brand-red) · ui/tabs (Radix · report-store
 *        canonical pill styling per IndustryReportSection L72-100) · Badge (rounded neutral
 *        bordered · for scope tags + revenue chips).
 *        Raw cards w/ DS tokens · NO accordion (wrong fit for content shape).
 *
 * Source: live kenresearch.com/australia-cold-chain-markets (re-scraped 2026-05-21).
 */

import { SectionLabel, Badge } from '@kenresearch/design-system/atoms';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@kenresearch/design-system/ui/tabs';
import { TABS_LIST_PRIMARY, TABS_TRIGGER_PRIMARY } from '@/lib/tab-styles';

// ─────────────────────────────────────────────────────────────────
// Tab 1 · Key Market Definition data
// ─────────────────────────────────────────────────────────────────

interface MarketDef {
  id: string;
  title: string;
  scope: string; // e.g. "Non-captive"
  tempRange: string; // e.g. "+10°C to -18°C"
  prose: string;
  revenueStreams: string[];
}

const KEY_MARKET_DEFS: MarketDef[] = [
  {
    id: 'cold-chain-market',
    title: 'Australia Cold Chain Market',
    scope: 'Non-captive',
    tempRange: '+10°C to -18°C',
    prose:
      'The market size has been calculated from revenue generated by non-captive cold storage logistics companies in Australia, operating in accredited cold storage warehouses owned and operated by them.',
    revenueStreams: [
      'Leasing revenues',
      'Packaging & labeling',
      'Loading and unloading charges',
      'Temperature monitoring',
      'Other value-added services',
    ],
  },
  {
    id: 'cold-transport-market',
    title: 'Australia Cold Transport Market',
    scope: 'Non-captive',
    tempRange: '+10°C to -18°C',
    prose:
      'Summation of revenues earned by non-captive cold transport companies, covering products such as meat and seafood, fruits and vegetables, vaccines and pharmaceuticals, dairy, bakery and confectionery — across domestic and international markets by land, sea and air cold transport.',
    revenueStreams: [
      'Freight forwarding',
      'Loading and unloading',
      'Distribution',
      'Last-mile delivery',
    ],
  },
];

// ─────────────────────────────────────────────────────────────────
// Tab 2 · Fundamental Definitions data
// ─────────────────────────────────────────────────────────────────

interface FundamentalDef {
  id: string;
  title: string;
  tempRange: string; // displayed prominently · tabular-nums
  /** Visual band · ambient (warm) · chiller (cool) · frozen (deep-cool) · scope (neutral) */
  band: 'ambient' | 'chiller' | 'frozen' | 'scope';
  description: string;
  /** Optional in/out-of-market-scope tag */
  scopeTag?: 'included' | 'excluded';
  scopeNote?: string;
}

const FUNDAMENTAL_DEFS: FundamentalDef[] = [
  {
    id: 'ambient',
    title: 'Ambient Storage',
    tempRange: '>+10°C',
    band: 'ambient',
    description:
      'Cold storage facilities that offer a temperature range above +10°C — used for shelf-stable goods that still require humidity or temperature regulation.',
  },
  {
    id: 'frozen',
    title: 'Frozen Storage',
    tempRange: '−18°C or colder',
    band: 'frozen',
    description:
      'Facilities at −18°C or colder. Includes chillers that can be converted to freezers, providing operational flexibility.',
  },
  {
    id: 'chiller',
    title: 'Chiller Storage',
    tempRange: '+1°C to −10°C',
    band: 'chiller',
    description:
      'Single-temperature facilities at +1°C to −10°C, non-convertible to any other range. Not prevalent in Australia.',
  },
  {
    id: 'captive',
    title: 'Captive / Owned Warehouses',
    tempRange: 'Own-use only',
    band: 'scope',
    description:
      'Cold storage warehouses owned and controlled by individual companies or conglomerates for their own product storage.',
    scopeTag: 'excluded',
    scopeNote: 'Not captured in market definition',
  },
  {
    id: 'non-captive',
    title: 'Non-Captive Warehouses',
    tempRange: '3PL & direct end-users',
    band: 'scope',
    description:
      'Cold storage warehouses owned by logistics companies and rented to customers. Demand comes from 3PL intermediaries and direct end-users (e.g. meat/seafood processors).',
    scopeTag: 'included',
    scopeNote: 'In market definition',
  },
];

// Temperature visual band colors · Ken data-viz palette (no off-palette raw rgba)
const BAND_STYLES: Record<FundamentalDef['band'], { bg: string; ring: string; label: string }> = {
  ambient: {
    // Category 1 · periwinkle-500 at 15% · warm temp visual
    bg: 'rgba(196, 198, 249, 0.15)',
    ring: 'rgba(196, 198, 249, 0.40)',
    label: 'var(--periwinkle-800, #7075c8)',
  },
  chiller: {
    // Category 2 · purple-500 at 10% · mid-cool visual
    bg: 'rgba(148, 136, 236, 0.10)',
    ring: 'rgba(148, 136, 236, 0.35)',
    label: 'var(--purple-700, #6f65c6)',
  },
  frozen: {
    // Category 3 · perano-800 at 12% · deep-cool visual
    bg: 'rgba(134, 179, 229, 0.12)',
    ring: 'rgba(134, 179, 229, 0.45)',
    label: 'rgba(80, 120, 170, 0.95)',
  },
  scope: {
    bg: 'var(--black-50, #fafafa)',
    ring: 'var(--black-200, #e5e5e5)',
    label: 'var(--semantic-ink-body)',
  },
};

// ─────────────────────────────────────────────────────────────────
// Components
// ─────────────────────────────────────────────────────────────────

function MarketDefCard({ def }: { def: MarketDef }) {
  return (
    <article className="rounded-[var(--radius-sm,10px)] border border-[var(--black-100)] bg-[var(--color-foundation-white)] p-6 space-y-4">
      {/* Title */}
      <h3
        className="font-display font-light text-[var(--semantic-ink-strong)]"
        style={{ fontSize: 'clamp(20px, 1.6vw, 24px)', lineHeight: 1.2, letterSpacing: '-0.01em' }}
      >
        {def.title}
      </h3>

      {/* Quick-facts chips */}
      <div className="flex flex-wrap gap-2">
        <Badge variant="rounded" size="sm" theme="neutral" bordered>
          {def.scope}
        </Badge>
        <Badge variant="rounded" size="sm" theme="neutral" bordered>
          {def.tempRange}
        </Badge>
      </div>

      {/* Prose */}
      <p className="font-body text-[15px] leading-[1.7] text-[var(--semantic-ink-body)]">
        {def.prose}
      </p>

      {/* Revenue streams */}
      <div>
        <p
          className="uppercase tracking-[0.12em] text-[var(--semantic-ink-muted)] mb-2"
          style={{ fontFamily: 'var(--font-sans)', fontSize: '11px', fontWeight: 600 }}
        >
          Revenue streams included
        </p>
        <ul className="space-y-1.5" role="list">
          {def.revenueStreams.map((rs) => (
            <li
              key={rs}
              className="font-body text-[14px] text-[var(--semantic-ink-body)] flex items-start gap-2"
            >
              <span
                aria-hidden="true"
                className="shrink-0 mt-[7px] w-1 h-1 rounded-full bg-[var(--semantic-ink-subtle)]"
              />
              <span>{rs}</span>
            </li>
          ))}
        </ul>
      </div>
    </article>
  );
}

function FundamentalDefCard({ def }: { def: FundamentalDef }) {
  const styles = BAND_STYLES[def.band];
  return (
    <article className="rounded-[var(--radius-sm,10px)] border border-[var(--black-100)] bg-[var(--color-foundation-white)] p-5 flex flex-col gap-3">
      {/* Temperature visual badge */}
      <div
        className="inline-flex items-center self-start gap-2 px-2.5 py-1 rounded-[var(--radius-xs,5px)]"
        style={{
          background: styles.bg,
          border: `1px solid ${styles.ring}`,
        }}
      >
        <span
          aria-hidden="true"
          className="w-2 h-2 rounded-full"
          style={{ background: styles.label }}
        />
        <span
          className="tabular-nums"
          style={{
            fontFamily: 'var(--font-sans)',
            fontSize: '12px',
            fontWeight: 600,
            color: styles.label,
            letterSpacing: '0.02em',
          }}
        >
          {def.tempRange}
        </span>
      </div>

      {/* Title */}
      <h3
        className="font-display font-light text-[var(--semantic-ink-strong)]"
        style={{ fontSize: '18px', lineHeight: 1.25, letterSpacing: '-0.005em' }}
      >
        {def.title}
      </h3>

      {/* Description */}
      <p className="font-body text-[14px] leading-[1.6] text-[var(--semantic-ink-body)] flex-1">
        {def.description}
      </p>

      {/* Scope tag */}
      {def.scopeTag && (
        <div className="flex items-center gap-1.5 pt-2 border-t border-[var(--black-50,#fafafa)]">
          <span
            aria-hidden="true"
            className="inline-block w-1.5 h-1.5 rounded-full"
            style={{
              background:
                def.scopeTag === 'included'
                  ? 'var(--semantic-ink-strong)'
                  : 'var(--semantic-ink-subtle)',
            }}
          />
          <span
            className="uppercase tracking-[0.1em]"
            style={{
              fontFamily: 'var(--font-sans)',
              fontSize: '10.5px',
              fontWeight: 600,
              color:
                def.scopeTag === 'included'
                  ? 'var(--semantic-ink-strong)'
                  : 'var(--semantic-ink-subtle)',
            }}
          >
            {def.scopeNote}
          </span>
        </div>
      )}
    </article>
  );
}

// ─────────────────────────────────────────────────────────────────
// Section
// ─────────────────────────────────────────────────────────────────

export function DefinitionsSection() {
  return (
    <section
      id="definitions"
      aria-labelledby="definitions-heading"
      className="px-4 sm:px-6 lg:px-12 max-w-[1100px] mx-auto w-full scroll-mt-[120px]"
    >
      {/* Eyebrow */}
      <div className="inline-flex mb-3">
        <SectionLabel background="light" variant="accent">
          Section 05 · Definitions
        </SectionLabel>
      </div>

      {/* H2 */}
      <h2
        id="definitions-heading"
        className="font-display font-light text-[clamp(28px,3vw,39px)] leading-[1.15] tracking-[-0.015em] text-[var(--semantic-ink-strong)] mb-3"
      >
        Australia Cold Chain Market definitions
      </h2>

      {/* Lede */}
      <p className="font-body text-[16px] leading-[1.6] text-[var(--semantic-ink-body)] max-w-[60ch] mb-8">
        Scope of the market sized in this report and the fundamental cold-storage temperature categories used throughout the analysis.
      </p>

      {/* Tabs · report-store canonical pill pattern */}
      <Tabs defaultValue="key-market" className="w-full">
        <TabsList className={TABS_LIST_PRIMARY}>
          {[
            { v: 'key-market', label: 'Key Market Definition' },
            { v: 'fundamental', label: 'Fundamental Definitions' },
          ].map((t) => (
            <TabsTrigger
              key={t.v}
              value={t.v}
              className={TABS_TRIGGER_PRIMARY}
            >
              {t.label}
            </TabsTrigger>
          ))}
        </TabsList>

        {/* Tab 1 · Key Market Definition · 2-card grid */}
        <TabsContent value="key-market" className="mt-0">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {KEY_MARKET_DEFS.map((def) => (
              <MarketDefCard key={def.id} def={def} />
            ))}
          </div>
        </TabsContent>

        {/* Tab 2 · Fundamental Definitions · 5-card grid */}
        <TabsContent value="fundamental" className="mt-0">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {FUNDAMENTAL_DEFS.map((def) => (
              <FundamentalDefCard key={def.id} def={def} />
            ))}
          </div>
        </TabsContent>
      </Tabs>
    </section>
  );
}
