'use client';

/**
 * FAQsSection — v0.4 §21 FAQs
 *
 * @what  Ported from V0_lite_report-legacy/FAQSection.tsx (canonical design).
 *        Single-open accordion · ChevronDown toggle · border card items ·
 *        "Still have questions?" CTA footer card.
 *        FAQ content: 12 Cold Chain Q&As (preserved from v0.4 original data).
 *
 * @why   Visual design IDENTICAL to v0-lite original · spacing · typography ·
 *        animation · colors. Tech team should not redesign same component twice.
 *
 * @when  v0.4 PDP body §21. Below §20 TOC · above §22 Sample Preview.
 *
 * Source: V0_lite_report-legacy (canonical) · ported 2026-05-22.
 *         FAQ copy: Ken Research client knowledge base · sales conversation logs · 2024.
 */

import { useState } from 'react';
import Link from 'next/link';
import { ChevronDown } from 'lucide-react';
import { SectionLabel, Button } from '@kenresearch/design-system/atoms';
import { motion, AnimatePresence } from 'framer-motion';

// ─────────────────────────────────────────────────────────────────
// FAQ Data — 12 Cold Chain Q&As
// TODO: replace w/ real CMS FAQ API
// ─────────────────────────────────────────────────────────────────

interface FAQItem {
  id: number;
  question: string;
  answer: string;
}

const faqs: FAQItem[] = [
  {
    id: 1,
    question: "What's included in this report?",
    answer:
      "The full report covers 24 sections: market sizing (2022–2027 historical + forecast), segmentation by end-user, temperature, region and transport mode, competitor landscape with share analysis, regulatory environment, future outlook with scenario modeling, and a full methodology appendix. Delivered as PDF + Excel dataset.",
  },
  {
    id: 2,
    question: 'Who is this report for?',
    answer:
      'Primary buyers are cold chain operators (logistics heads · BD leads), private equity and M&A teams evaluating Australia cold chain investments, FMCG and pharma logistics managers, and government/trade bodies tracking sector KPIs. Secondary buyers include consultants and academics benchmarking Australia against APAC peers.',
  },
  {
    id: 3,
    question: 'How recent is the data?',
    answer:
      'Primary research field work ran Q3–Q4 2024 (30+ CATI interviews with Tier-1 and Tier-2 cold chain operators). Secondary data sources updated through Q1 2025 (ABS Cat. 8731, ASX filings, RWTA directory, TGA cold-chain guidelines). The forecast model was finalized in March 2025.',
  },
  {
    id: 4,
    question: 'Can I get a sample before purchase?',
    answer:
      'Yes. A 3-page sample is available covering: executive summary, one market-size chart figure, and a competitor snapshot table. Request the sample via "Talk to expert" above or preview directly from §22 on this page. The sample is delivered as PDF within one business day.',
  },
  {
    id: 5,
    question: 'How is market sizing calculated?',
    answer:
      'Market size is calculated as total revenue generated by non-captive cold chain operators in Australia (cold storage warehousing + cold transport). Revenue triangulated from: (1) 30+ operator-disclosed P&Ls under NDA, (2) ABS Cat. 8731 refrigerated warehousing census, (3) ASX public filings for listed players, and (4) Ken proprietary demand-model cross-validation. Captive (in-house) cold chain is excluded.',
  },
  {
    id: 6,
    question: "What's the difference between cold storage and cold transport in this report?",
    answer:
      'Cold Storage covers revenue from non-captive accredited cold storage warehouses (leasing, handling, labeling, temperature monitoring). Cold Transport covers revenue from refrigerated freight forwarding, domestic distribution, last-mile delivery, and intermodal reefer. Both are non-captive only — Woolworths Primary Connect and Coles SCM in-house operations are excluded from market size but included in end-user analysis.',
  },
  {
    id: 7,
    question: 'Does the forecast account for regulatory changes?',
    answer:
      'Yes. The 2022–2027 forecast integrates three regulatory scenarios: baseline (existing TGA + FSANZ + AFCC compliance costs), upside (Energy Performance Standards for refrigerated transport enacted by 2026), and downside (ASEAN FTA fast-track disrupts domestic operator pricing). Scenario modeling is covered in §16 Future Outlook.',
  },
  {
    id: 8,
    question: 'How are competitor revenues estimated?',
    answer:
      'For ASX/NYSE listed players (Americold, Lineage/listed entities, Coles Group), revenues are from public SEC/ASX filings with Australia/ANZ segment disclosed. For private operators (NewCold, Swire, Kalfresh, Emergent), revenues are triangulated from: (1) NDA-protected operator interviews, (2) pallet-position × average rate per Ken field survey, (3) RWTA membership data cross-validated. All private estimates carry ±8–12% margin of error, disclosed in the appendix.',
  },
  {
    id: 9,
    question: 'Can I get a custom cut (state/segment/year)?',
    answer:
      'Yes. Custom cuts are available for any combination of: state/territory (all 8), sub-segment (cold storage vs cold transport vs frozen vs chiller), end-user vertical (meat/seafood · pharma · dairy · produce · retail · e-grocery), and year-range. Custom cuts are quoted separately and typically delivered within 10 business days. Contact us via "Talk to expert" to scope.',
  },
  {
    id: 10,
    question: "What's the refund policy?",
    answer:
      'Reports are non-refundable once delivered (standard B2B research industry policy), as the full intellectual property is transferred on delivery. We offer a sample preview (§22) and expert consultation before purchase to ensure fit. For enterprise licenses, customization scope is agreed upfront before contract. Contact us with concerns before purchase.',
  },
  {
    id: 11,
    question: 'How do I cite this report?',
    answer:
      'Recommended citation: Ken Research (2025). Australia Cold Chain Market Outlook 2022–2027. Ken Research Private Limited. Available at: kenresearch.com. For academic citation use APA 7th format. For client deliverables, the license terms include right to cite with attribution. Do not reproduce charts or tables in full without written permission.',
  },
  {
    id: 12,
    question: 'Who do I talk to for licensing / enterprise?',
    answer:
      'Enterprise and multi-seat licensing (3+ users · department access · annual update subscriptions) is handled by our enterprise accounts team. Use "Talk to expert" above or email enterprise@kenresearch.com. Typical turnaround for enterprise quote: 1 business day. Volume discounts apply for 5+ report bundles or annual research subscriptions.',
  },
];

// ─────────────────────────────────────────────────────────────────
// Component
// ─────────────────────────────────────────────────────────────────

export function FAQsSection() {
  const [openFaqId, setOpenFaqId] = useState<number | null>(1);

  const toggleFaq = (id: number) => {
    setOpenFaqId(openFaqId === id ? null : id);
  };

  return (
    <section
      id="faq"
      aria-label="Frequently Asked Questions"
      className="px-4 sm:px-6 lg:px-12 max-w-[880px] mx-auto w-full"
    >
      {/* Eyebrow + heading */}
      <div className="max-w-3xl mb-12">
        <div className="inline-flex mb-3">
          <SectionLabel background="light" variant="accent">
            Section 21 · FREQUENTLY ASKED
          </SectionLabel>
        </div>
        <h2
          className="font-display font-light text-[clamp(24px,2.6vw,36px)] leading-[1.1] tracking-tight text-[var(--semantic-ink-strong)] mb-3"
          style={{ letterSpacing: '-0.015em' }}
        >
          Frequently Asked Questions
        </h2>
        <p className="text-[1rem] text-[var(--black-500)] mt-4 leading-relaxed">
          12 questions answered · sourced from sales calls, client onboarding, and analyst conversations.
        </p>
      </div>

      {/* Accordion items */}
      <div className="space-y-4">
        {faqs.map((faq) => {
          const isOpen = openFaqId === faq.id;
          return (
            <div
              key={faq.id}
              className="border border-black/10 rounded-[10px] overflow-hidden
                hover:border-black/25 transition-colors duration-200"
            >
              <button
                onClick={() => toggleFaq(faq.id)}
                id={`faq-question-${faq.id}`}
                className="w-full px-4 sm:px-6 py-4 sm:py-5 flex items-center justify-between text-left
                  hover:bg-black/[0.02] transition-colors duration-200 group"
                aria-expanded={isOpen}
                aria-controls={`faq-answer-${faq.id}`}
              >
                <span className="text-[1rem] font-medium text-black pr-4 leading-relaxed">
                  {faq.question}
                </span>
                <ChevronDown
                  className={`h-5 w-5 flex-shrink-0 transition-transform duration-300 text-[var(--black-500)] ${
                    isOpen ? 'rotate-180' : ''
                  }`}
                  strokeWidth={2}
                />
              </button>

              <AnimatePresence initial={false}>
                {isOpen && (
                  <motion.div
                    key="answer"
                    id={`faq-answer-${faq.id}`}
                    role="region"
                    aria-labelledby={`faq-question-${faq.id}`}
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.25, ease: 'easeInOut' }}
                    className="overflow-hidden"
                  >
                    <div className="px-4 sm:px-6 pb-4 sm:pb-5 text-[1rem] text-[var(--black-500)] leading-relaxed pt-4">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>

      {/* Contact CTA */}
      <div className="mt-10 sm:mt-12 text-left p-5 sm:p-8 rounded-[10px] bg-black/[0.02] border border-black/10 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <p className="text-[1rem] text-black mb-2">
            Still have questions?
          </p>
          <p className="text-[0.875rem] text-[var(--black-500)]">
            Our research team is here to help you find the right solution
          </p>
        </div>
        {/* P0-fix 2026-05-22 · DS Button atom · secondary light · animatedArrow · wraps Next Link for navigation */}
        <Link href="/contact" className="flex-shrink-0">
          <Button variant="secondary" size="sm" animatedArrow aria-label="Contact Research Team">
            Contact Research Team
          </Button>
        </Link>
      </div>
    </section>
  );
}
